#!/usr/bin/env bash
#
# Builds a production, release-signed Android APK.
#
# `android/` is gitignored and regenerated by `expo prebuild` on every run, so
# the release keystore cannot live in `android/app/build.gradle` — the template
# there hardcodes `signingConfig signingConfigs.debug` and would come back on the
# next prebuild. The keystore is injected as Gradle properties instead, which
# survive regeneration and keep the secret out of the repo entirely.
#
# Required environment (see README):
#   RASPORED_KEYSTORE           absolute path to the release keystore
#   RASPORED_KEYSTORE_PASSWORD  store password
#   RASPORED_KEY_ALIAS          key alias inside the store
#   RASPORED_KEY_PASSWORD       key password
#
# Optional:
#   RASPORED_MINIFY=true        enable R8 + resource shrinking (test before shipping:
#                               shrinking can strip reflection-reached native modules)
#   RASPORED_TASK=bundleRelease produce an .aab for Play instead of an .apk

set -euo pipefail

missing=()
for var in RASPORED_KEYSTORE RASPORED_KEYSTORE_PASSWORD RASPORED_KEY_ALIAS RASPORED_KEY_PASSWORD; do
  [[ -n "${!var:-}" ]] || missing+=("$var")
done
if (( ${#missing[@]} > 0 )); then
  echo "error: missing required environment: ${missing[*]}" >&2
  echo "Without these the build would silently fall back to the debug keystore." >&2
  exit 1
fi
if [[ ! -f "$RASPORED_KEYSTORE" ]]; then
  echo "error: keystore not found at $RASPORED_KEYSTORE" >&2
  exit 1
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

minify="${RASPORED_MINIFY:-false}"
task="${RASPORED_TASK:-assembleRelease}"

# --clean discards any drift in the generated project, so the build reflects
# app.json and nothing else.
npx expo prebuild --platform android --no-install --clean

cd android
./gradlew "$task" \
  -Pandroid.injected.signing.store.file="$RASPORED_KEYSTORE" \
  -Pandroid.injected.signing.store.password="$RASPORED_KEYSTORE_PASSWORD" \
  -Pandroid.injected.signing.key.alias="$RASPORED_KEY_ALIAS" \
  -Pandroid.injected.signing.key.password="$RASPORED_KEY_PASSWORD" \
  -Pandroid.enableMinifyInReleaseBuilds="$minify" \
  -Pandroid.enableShrinkResourcesInReleaseBuilds="$minify"
cd "$root"

artifact="$(find android/app/build/outputs -name '*-release.apk' -o -name '*-release.aab' | head -1)"
echo
echo "Built: $artifact"

# Fail loudly if the APK still carries the debug identity, which is the one
# mistake that is invisible until Play rejects the upload.
if [[ "$artifact" == *.apk ]] && command -v apksigner >/dev/null 2>&1; then
  if apksigner verify --print-certs "$artifact" | grep -qi "CN=Android Debug"; then
    echo "error: artifact is signed with a debug certificate" >&2
    exit 1
  fi
  echo "Signed with the release certificate."
fi
